#!/usr/bin/env python3
"""
Concurrency risk diagnostic: why the frozen liquidation-cascade reversion strategy reaches
up to 18 simultaneously-open positions, and whether it should.

The engine opens a fresh fixed-notional 5-min round-trip on EVERY qualifying tail event with
no position cap, no netting, no cooldown, no size decay. When cascades cluster (many >=98th
tail events in minutes, same-direction during a one-way cascade), the positions stack. This
script quantifies that stacking and its statistical consequences, and evaluates counterfactual
position caps as a pure filter on the already-realized frozen trades (no new fills, so the
spent OOS holdout is untouched -- the caps are a risk overlay).

Sections per trade set (OOS frozen; TRAIN generated by gen_train_trades.py):
  1. Concurrency structure + directional concentration.
  2. Effective sample size (episode clustering) + cluster-robust / block-bootstrap SE of the
     edge -- does t_NW 2.62 survive the overlap?
  3. P&L and drawdown concentration + attribution (exclude the peak episode).
  4. Leave-one-day / leave-one-episode-out jackknife influence.
  5. Counterfactual caps (cap-at-N-concurrent, 1-per-episode): Sharpe, MtM drawdown, edge,
     peak capital -- the edge-vs-risk frontier.

Usage (run from repo root, after gen_train_trades.py has produced the train CSV):
  python strategies/concurrency_analysis.py
"""

from __future__ import annotations

import sys as _sys
from pathlib import Path as _Path

_sys.path.insert(0, str(_Path(__file__).resolve().parents[1]))

import sys
from datetime import timedelta
from pathlib import Path

import numpy as np
import polars as pl

from backtester import BookProvider
from significance import hac_stats
from backtest_oos_test import peak_capital, TEST_START, TEST_END
from backtest_oos_risk import mtm_max_drawdown, realized_close_dd

NOTIONAL = 50_000.0
OOS_CSV = Path("data/results/oos_test_trades.csv")
TRAIN_CSV = Path("data/results/train_filtered_trades.csv")
OUT_CSV = Path("data/results/concurrency_policy_summary.csv")
DT_COLS = ["decision_time", "liquidation_time", "entry_start_time", "entry_end_time",
           "exit_start_time", "exit_end_time"]
GAPS = (timedelta(0), timedelta(seconds=60), timedelta(minutes=5))


def _eprint(*a: object) -> None:
    print(*a, file=sys.stderr, flush=True)


def load(path: Path) -> pl.DataFrame:
    df = pl.read_csv(path)
    for c in DT_COLS:
        if c in df.columns:
            df = df.with_columns(pl.col(c).str.to_datetime(time_zone="UTC"))
    return df.filter(pl.col("keep")).sort("decision_time")


def net_bps(df: pl.DataFrame) -> np.ndarray:
    return (1e4 * df["net_pnl"] / NOTIONAL).to_numpy()


# ---------------------------------------------------------------------------
# 1. Concurrency structure
# ---------------------------------------------------------------------------

def concurrency_profile(df: pl.DataFrame) -> dict:
    """Sweep line over [entry_start, exit_end] tracking count and net signed direction.

    `counts` are per-event-point (used for the >=k transition table). The one-way fraction is
    DURATION-weighted (D3): we integrate, over each constant-state segment, the time the open
    book is fully one-directional (|net| == count) divided by total open time -- an honest
    wall-clock fraction, not a count of transitions."""
    opens = df["entry_start_time"].to_list()
    closes = df["exit_end_time"].to_list()
    dirs = df["direction"].to_list()
    ev = [(t, +1, d) for t, d in zip(opens, dirs)] + [(t, -1, d) for t, d in zip(closes, dirs)]
    ev.sort(key=lambda e: (e[0], -e[1]))  # opens before closes on a tie
    cur = net = 0
    peak = 0
    peak_t = None
    counts = []
    open_dur = 0.0
    oneway_dur = 0.0
    prev_t = ev[0][0] if ev else None
    for t, delta, d in ev:
        seg = (t - prev_t).total_seconds()  # duration of the segment before this event
        if cur > 0:
            open_dur += seg
            if abs(net) == cur:
                oneway_dur += seg
        cur += delta
        net += delta * d
        counts.append(cur)
        if cur > peak:
            peak, peak_t = cur, t
        prev_t = t
    counts = np.array(counts)
    open_pts = counts[counts > 0]
    return {
        "peak": int(peak),
        "peak_time": peak_t,
        "counts": counts,
        "frac_open_time_oneway": float(oneway_dur / open_dur) if open_dur > 0 else float("nan"),
        "mean_when_open": float(open_pts.mean()) if len(open_pts) else 0.0,
    }


# ---------------------------------------------------------------------------
# 2. Episodes / effective sample size
# ---------------------------------------------------------------------------

def assign_episodes(df: pl.DataFrame, gap: timedelta) -> np.ndarray:
    """Chain trades into episodes: a new episode starts when a trade's entry_start exceeds
    the running max exit_end of the current episode by more than `gap`.

    We attach an explicit original-row index and carry it through a single stable sort, so the
    label mapping does not depend on polars sort-order being reproducible across two separate
    sorts (see R1)."""
    df2 = df.with_row_index("_orig")
    order = df2.sort("entry_start_time", maintain_order=True)
    starts = order["entry_start_time"].to_list()
    ends = order["exit_end_time"].to_list()
    orig = order["_orig"].to_numpy()
    ep_of_sorted = np.empty(len(df), dtype=int)
    ep = -1
    running_end = None
    for i, (s, e) in enumerate(zip(starts, ends)):
        if running_end is None or s > running_end + gap:
            ep += 1
            running_end = e
        else:
            running_end = max(running_end, e)
        ep_of_sorted[i] = ep
    # scatter labels back to original row positions via the carried index (no second sort)
    out = np.empty(len(df), dtype=int)
    out[orig] = ep_of_sorted
    return out


def effective_n(ep: np.ndarray) -> dict:
    sizes = np.bincount(ep)
    n = int(sizes.sum())
    n_eff = float(n ** 2 / (sizes ** 2).sum())
    return {"n": n, "episodes": int(len(sizes)), "n_eff": n_eff,
            "max_episode": int(sizes.max()), "mean_episode": float(sizes.mean())}


def cluster_robust_t(y: np.ndarray, ep: np.ndarray) -> dict:
    """Cluster-robust SE/t of the mean, clustering by episode (finite-cluster corrected)."""
    n = len(y)
    mean = float(y.mean())
    r = y - mean
    groups = np.unique(ep)
    g = len(groups)
    if g < 2:
        # one cluster => no between-cluster variation => no inference (residuals sum to ~0).
        return {"mean": mean, "se_cluster": 0.0, "t_cluster": float("nan"), "n_clusters": g}
    ss = sum(float(r[ep == c].sum()) ** 2 for c in groups)
    corr = g / (g - 1)
    var = corr * ss / n ** 2
    se = float(np.sqrt(var))
    return {"mean": mean, "se_cluster": se, "t_cluster": mean / se if se else float("nan"),
            "n_clusters": g}


def episode_block_bootstrap(y: np.ndarray, ep: np.ndarray, n_boot: int = 5000,
                            seed: int = 0) -> tuple[float, float, float, float]:
    """Resample whole episodes with replacement; return the mean-edge 90% CI and the fraction
    of the resampling distribution at or below zero. That fraction is a descriptive
    'does the CI clear 0' statistic (share of bootstrap means <= 0), NOT a null-recentered
    hypothesis-test p-value (D6) -- reported as `boot_frac<=0`."""
    rng = np.random.default_rng(seed)
    groups = np.unique(ep)
    by_ep = [y[ep == c] for c in groups]
    g = len(groups)
    means = np.empty(n_boot)
    for b in range(n_boot):
        pick = rng.integers(0, g, size=g)
        pooled = np.concatenate([by_ep[i] for i in pick])
        means[b] = pooled.mean()
    lo, hi = np.percentile(means, [5, 95])
    frac_le0 = float((means <= 0).mean())
    return float(lo), float(np.median(means)), float(hi), frac_le0


# ---------------------------------------------------------------------------
# 3/5. Metrics for a trade subset (used for the whole set and for capped subsets)
# ---------------------------------------------------------------------------

def annualized_sharpe(df: pl.DataFrame, span_start, span_end) -> float:
    """sqrt(365) daily-P&L Sharpe over the calendar span (idle days = 0), the as-coded
    convention. Only meaningful for the OOS span; passed explicit bounds."""
    closes = df["decision_time"].dt.offset_by("5m").dt.date()
    daily = (df.with_columns(close_date=closes).group_by("close_date")
             .agg(pl.col("net_pnl").sum()).sort("close_date"))
    all_days = pl.date_range(span_start.date(), (span_end - timedelta(days=1)).date(),
                             interval="1d", eager=True)
    cal = pl.DataFrame({"close_date": all_days}).join(daily, on="close_date", how="left").fill_null(0.0)
    d = cal["net_pnl"].to_numpy()
    sd = d.std(ddof=1)
    return float(d.mean() / sd * np.sqrt(365)) if sd > 0 else float("nan")


def subset_metrics(df: pl.DataFrame, book: BookProvider, label: str,
                   span_start=None, span_end=None, compute_mtm: bool = True) -> dict:
    y = net_bps(df)
    s = hac_stats(df.sort("decision_time").pipe(lambda d: (1e4 * d["net_pnl"] / NOTIONAL).to_numpy()))
    # Report peak concurrency on the SAME [entry_start, exit_end) interval the cap enforces
    # (R2), so a capped subset's reported peak can never exceed its cap.
    pk = concurrency_profile(df)["peak"] if len(df) else 0
    pk_cap = pk * NOTIONAL
    mtm = mtm_max_drawdown(df, book)["max_dd_usd"] if compute_mtm else float("nan")
    sharpe = annualized_sharpe(df, span_start, span_end) if span_start is not None else float("nan")
    return {
        "policy": label,
        "trades": len(df),
        "net_bps": round(float(y.mean()), 2),
        "t_nw": round(float(s["t_nw"]), 2),
        "total_net_usd": round(float(df["net_pnl"].sum()), 0),
        "peak_concurrent": pk,
        "peak_capital_usd": round(pk_cap, 0),
        "ann_sharpe": round(sharpe, 2) if sharpe == sharpe else None,
        "realized_dd_usd": round(realized_close_dd(df), 0),
        "mtm_dd_usd": round(mtm, 0) if mtm == mtm else None,
        "mtm_dd_pct_peakcap": round(mtm / pk_cap * 100, 2) if (compute_mtm and pk_cap) else None,
    }


# ---------------------------------------------------------------------------
# 5. Counterfactual position caps (pure filter on realized trades)
# ---------------------------------------------------------------------------

def cap_at_n(df: pl.DataFrame, n: int) -> pl.DataFrame:
    """Greedy time-ordered cap: open a trade only if fewer than n are currently open;
    otherwise skip it (a missed trade, not deferred). Concurrency measured on
    [entry_start, exit_end)."""
    order = df.sort("entry_start_time")
    starts = order["entry_start_time"].to_list()
    ends = order["exit_end_time"].to_list()
    open_ends: list = []
    taken = np.zeros(len(order), dtype=bool)
    for i, (s, e) in enumerate(zip(starts, ends)):
        open_ends = [x for x in open_ends if x > s]  # release positions closed by s
        if len(open_ends) < n:
            taken[i] = True
            open_ends.append(e)
    return order.filter(pl.Series(taken))


def dedupe_per_episode(df: pl.DataFrame, gap: timedelta, by: str = "displacement_bps") -> pl.DataFrame:
    """Keep one trade per episode: the max-`by` (most violent) trade in each cluster.

    ORACLE (look-ahead): selecting a cluster's global max needs to observe trades that arrive
    after the first trade's decision -- an upper bound, not a live rule (see the report).
    D2 fixes: raise if the key is missing (no silent metric swap), drop null/NaN keys so they
    cannot sort to the top under descending, and break ties deterministically by decision_time."""
    if by not in df.columns:
        raise ValueError(f"dedupe key {by!r} not in trade columns")
    ep = assign_episodes(df, gap)
    d = (df.with_columns(pl.Series("_ep", ep))
         .filter(pl.col(by).is_not_null() & pl.col(by).is_not_nan()))
    return (d.sort([by, "decision_time"], descending=[True, False])
            .unique(subset=["_ep"], keep="first")
            .drop("_ep").sort("decision_time"))


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def analyze(df: pl.DataFrame, label: str, book: BookProvider,
            span_start=None, span_end=None, compute_mtm: bool = True) -> list[dict]:
    print("\n" + "=" * 78)
    print(f"# {label}  ({len(df)} filtered trades)")
    print("=" * 78)

    prof = concurrency_profile(df)
    counts = prof["counts"]
    print(f"\n[1] CONCURRENCY  peak={prof['peak']} at {prof['peak_time']}   "
          f"mean-when-open={prof['mean_when_open']:.2f}   "
          f"one-way fraction of open TIME={prof['frac_open_time_oneway']*100:.0f}% (duration-weighted)")
    for thr in (1, 2, 3, 5, 8, 12, 18):
        print(f"    >= {thr:2d} concurrent: {int((counts >= thr).sum()):4d} event-points")

    print("\n[2] EFFECTIVE SAMPLE SIZE + DEPENDENCE (episode clustering; sensitivity to gap tau)")
    print("    N_eff is the Kish rho=1 WORST CASE (assumes within-cluster P&L correlation = 1);")
    print("    the cluster-t / bootstrap below are the honest inference -- directional overlap")
    print("    (one-way) is NOT the same as P&L correlation, so they beat the conservative t_NW.")
    y = net_bps(df)
    for gap in GAPS:
        ep = assign_episodes(df, gap)
        en = effective_n(ep)
        cr = cluster_robust_t(y, ep)
        lo, med, hi, frac = episode_block_bootstrap(y, ep)
        gl = "overlap" if gap == timedelta(0) else f"+{int(gap.total_seconds())}s"
        print(f"  tau={gl:>8}: {en['episodes']:3d} episodes, N_eff={en['n_eff']:5.1f} "
              f"(of {en['n']}), max ep={en['max_episode']:2d}   "
              f"cluster t={cr['t_cluster']:+.2f}   "
              f"boot mean [{lo:+.1f},{hi:+.1f}] frac<=0={frac:.3f}")
    # day-level clustering, so episode-clustering can't be accused of convenient granularity (R3)
    day_codes = df["decision_time"].dt.date().to_physical().to_numpy()
    crd = cluster_robust_t(y, day_codes)
    iid = hac_stats(y)
    print(f"    estimator ladder: t_IID {iid['t_iid']:+.2f} | cluster-by-episode "
          f"{cluster_robust_t(y, assign_episodes(df, timedelta(0)))['t_cluster']:+.2f} | "
          f"cluster-by-day {crd['t_cluster']:+.2f} | t_NW {iid['t_nw']:+.2f} (conservative)")

    print("\n[3] P&L / DD CONCENTRATION")
    d = df.with_columns(day=pl.col("decision_time").dt.date())
    by_day = d.group_by("day").agg(pl.col("net_pnl").sum().alias("pnl"),
                                   pl.len().alias("n")).sort("pnl", descending=True)
    total = float(df["net_pnl"].sum())
    top = by_day.head(1)
    top_day = top["day"][0]; top_pnl = float(top["pnl"][0]); top_n = int(top["n"][0])
    print(f"    active days={by_day.height}   top day {top_day}: {top_n} trades, "
          f"${top_pnl:,.0f} = {top_pnl/total*100:.0f}% of ${total:,.0f}   "
          f"top-3 days share: {by_day['pnl'].head(3).sum()/total*100:.0f}%")
    if compute_mtm:
        full_dd = mtm_max_drawdown(df, book)["max_dd_usd"]
        ex = df.filter(pl.col("decision_time").dt.date() != top_day)
        ex_dd = mtm_max_drawdown(ex, book)["max_dd_usd"]
        # attribution is only valid if the excluded day is also the DD-driving day (R5): the
        # collapse of the DD on exclusion confirms it directly.
        print(f"    MtM DD full ${full_dd:,.0f}   excl {top_day} ${ex_dd:,.0f}   "
              f"=> {top_day} accounts for ${full_dd-ex_dd:,.0f} "
              f"({(full_dd-ex_dd)/full_dd*100:.0f}% of DD)")

    print("\n[4] JACKKNIFE (leave-one-day-out influence on mean net bps)")
    base = float(net_bps(df).mean())
    infl = []
    for day in by_day["day"].to_list():
        sub = df.filter(pl.col("decision_time").dt.date() != day)
        infl.append((day, float(net_bps(sub).mean()) - base))
    infl.sort(key=lambda x: x[1])  # most negative delta = most positively influential day
    worst = infl[0]
    ex_worst = df.filter(pl.col("decision_time").dt.date() != worst[0])
    ep0 = assign_episodes(ex_worst, timedelta(0))
    cr0 = cluster_robust_t(net_bps(ex_worst), ep0)
    print(f"    dropping {worst[0]} moves mean edge by {worst[1]:+.2f} bps "
          f"(most influential day)")
    print(f"    edge without {worst[0]}: mean {net_bps(ex_worst).mean():+.2f} bps, "
          f"cluster t {cr0['t_cluster']:+.2f}, t_NW {hac_stats(net_bps(ex_worst.sort('decision_time')))['t_nw']:+.2f}")

    print("\n[5] COUNTERFACTUAL POSITION CAPS (filter on realized trades)")
    rows = [subset_metrics(df, book, "uncapped (N=inf)", span_start, span_end, compute_mtm)]
    for n in (5, 3, 2, 1):
        rows.append(subset_metrics(cap_at_n(df, n), book, f"cap N={n}", span_start, span_end, compute_mtm))
    rows.append(subset_metrics(dedupe_per_episode(df, timedelta(0)), book,
                               "1-per-ep ORACLE(maxdisp)", span_start, span_end, compute_mtm))
    tbl = pl.DataFrame(rows)
    pl.Config.set_tbl_rows(20); pl.Config.set_tbl_cols(20); pl.Config.set_tbl_width_chars(220)
    print(tbl)
    return [{**r, "set": label} for r in rows]


def main() -> None:
    book = BookProvider()
    all_rows: list[dict] = []

    _eprint("analyzing OOS ...")
    oos = load(OOS_CSV)
    all_rows += analyze(oos, "OOS 2024-06-25..10-14 (filtered $50k)", book,
                        span_start=TEST_START, span_end=TEST_END, compute_mtm=True)

    if TRAIN_CSV.exists():
        _eprint("analyzing TRAIN ...")
        train = load(TRAIN_CSV)
        # MtM DD over a full train year is many book passes; report realized-close for the
        # cap table on train and MtM only for the uncapped set (kept cheap + honest).
        # MtM omitted on train (a full-year book-tick pass reloads ~365 day-files and is very
        # slow); realized-close DD + peak capital + concurrency structure carry the train story.
        all_rows += analyze(train, "TRAIN 2023-06-25..2024-06-24 (filtered $50k)", book,
                            span_start=None, span_end=None, compute_mtm=False)
    else:
        _eprint(f"(train CSV {TRAIN_CSV} not found -- run gen_train_trades.py; OOS-only report)")

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    pl.DataFrame(all_rows).write_csv(OUT_CSV)
    _eprint(f"wrote {OUT_CSV}")


if __name__ == "__main__":
    main()
